[package]
name = "my-rust-api"
version = "0.1.0"
authors = ["Ugho STEPHAN <stephan.ugho@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "0.7"
listenfd = "0.3"
log = "0.4.0"
env_logger = "0.6.0"
